package xiaozhi.common.utils;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

public class AESUtilsTest {

    @Test
    public void testEncryptAndDecrypt() {
        String key = "xiaozhi1234567890";
        String plainText = "Hello, LittleWise!";

        System.out.println("Original text: " + plainText);
        System.out.println("key: " + key);

        // Encrypt
        String encrypted = AESUtils.encrypt(key, plainText);
        System.out.println("Encrypted result: " + encrypted);

        // Decrypt
        String decrypted = AESUtils.decrypt(key, encrypted);
        System.out.println("Decrypted result: " + decrypted);

        // Verify
        assertEquals(plainText, decrypted, "Encryption and decryption results should be consistent");
        System.out.println("Encrypt/decrypt consistent: " + plainText.equals(decrypted));
    }

    @Test
    public void testDifferentKeyLengths() {
        String[] keys = {
                "1234567890123456", // 16 bit
                "123456789012345678901234", // 24 bit
                "12345678901234567890123456789012", // 32 bit
                "short", // short key
                "verylongkeythatwillbetruncatedto32bytes" // long key
        };

        String plainText = "Test text";

        for (String key : keys) {
            String encrypted = AESUtils.encrypt(key, plainText);
            String decrypted = AESUtils.decrypt(key, encrypted);
            assertEquals(plainText, decrypted, "Key length: " + key.length());
        }
    }

    @Test
    public void testSpecialCharacters() {
        String key = "xiaozhi1234567890";
        String[] testTexts = {
                "Hello World",
                "Hello, world",
                "Hello, LittleWise!",
                "Special characters: !@#$%^&*()",
                "Mixed numbers 123 and text",
                "Emoji: 😀🎉🚀",
                "Empty string test",
                ""
        };

        for (String text : testTexts) {
            String encrypted = AESUtils.encrypt(key, text);
            String decrypted = AESUtils.decrypt(key, encrypted);
            assertEquals(text, decrypted, "Test text: " + text);
        }
    }

    @Test
    public void testCrossLanguageCompatibility() {
        // These are encryption results generated by the Python version, used to test cross-language compatibility
        String key = "xiaozhi1234567890";
        String plainText = "Hello, LittleWise!";

        // Encryption result generated by the Python version (obtained after running a Python test)
        // String pythonEncrypted = "encrypted result obtained from the Python test";
        // String decrypted = AESUtils.decrypt(key, pythonEncrypted);
        // assertEquals(plainText, decrypted, "Java should be able to decrypt the Python encrypted result");

        // Generate a Java encryption result for Python to test
        String javaEncrypted = AESUtils.encrypt(key, plainText);
        System.out.println("Java encryption result for Python testing: " + javaEncrypted);
    }
}
